export const USER_AUTH_START = 'USER_AUTH_START';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';

export const SHOW_LOGIN = "SHOW_LOGIN";
export const SHOW_SIGNUP = "SHOW_SIGNUP";
export const CLOSE_MODAL = "CLOSE_MODAL";

// export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const TEACHER_LOGOUT = "TEACHER_LOGOUT";
export const STUDENT_LOGOUT = 'STUDENT_LOGOUT';

export const GET_BRANCHES_SUCCESS = "GET_BRANCHES_SUCCESS";

export const STUDENT_VIDEOS_START = 'STUDENT_VIDEOS_START';
export const STUDENT_VIDEOS_SUCCESS = 'STUDENT_VIDEOS_SUCCESS';
export const STUDENT_VIDEOS_FAIL = 'STUDENT_VIDEOS_FAIL';
